version: "3"

services: 

  app: 
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: devtraining-app
    ports: 
      - "3001:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    build: .docker/postgres 
    container_name: devtraining-db
    restart: always
    tty: true 
    ports: 
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dinis1981!$ 
      - POSTGRES_DB=devtraining 

  pgadmin:
    image: dpage/pgadmin4
    container_name: devtraining-pgadmin
    tty: true 
    env_file:
      .env
    ports:
      - "8000:80"
    depends_on:
      - db